apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
  labels:
    {{- include "vprofile.labels" . | nindent 4 }}
spec:
  selector:
    app: vproapp
  ports:
    - name: vpro-port
      protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: vproapp-port
  type: ClusterIP
