apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-claim
  labels:
    {{- include "vprofile.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.db.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.db.storage }}
