apiVersion: v1
kind: Service
metadata:
  name: vprodb
  labels:
    {{- include "vprofile.labels" . | nindent 4 }}
spec:
  selector:
    app: vprodb
  ports:
    - name: db-svc
      protocol: TCP
      port: {{ .Values.db.port }}
      targetPort: vprodb-port
  type: ClusterIP
