apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
    {{- include "vprofile.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      initContainers:
        - name: busybox
          image: busybox:latest
          command: ["sh", "-c", "rm -rf /var/lib/mysql/lost+found"]
          volumeMounts:
            - name: vpro-db-data
              mountPath: /var/lib/mysql
      containers:
        - name: vprodb
          image: {{ .Values.db.image }}
          ports:
            - name: vprodb-port
              containerPort: {{ .Values.db.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_password
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
      volumes:
        - name: vpro-db-data
          persistentVolumeClaim:
            claimName: db-volume-claim
