apiVersion: v1
kind: Service
metadata:
  name: vprocache01
  labels:
    {{- include "vprofile.labels" . | nindent 4 }}
spec:
  selector:
    app: memcached
  ports:
    - protocol: TCP
      port: {{ .Values.memcache.port }}
      targetPort: memcachedport
  type: ClusterIP
