apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01
  labels:
    app: rabbitmq
    {{- include "vprofile.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          ports:
            - name: rabbitmqport
              containerPort: {{ .Values.rabbitmq.port }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.user | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: rmq_password
