apiVersion: v1
kind: Service
metadata:
  name: vpromq01
  labels:
    {{- include "vprofile.labels" . | nindent 4 }}
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-svc-port
      protocol: TCP
      port: {{ .Values.rabbitmq.port }}
      targetPort: rabbitmqport
  type: ClusterIP
