apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    {{- include "vprofile.labels" . | nindent 4 }}
type: Opaque
data:
  db_password: {{ .Values.db.password }}
  rmq_password: {{ .Values.rabbitmq.password }}
