apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  selector:
    app: rabbitmq
  ports:
  - name: rabbitmq-svc-port 
    protocol: TCP
    port: 5672
    targetPort: rabbitmqport
  type: ClusterIP