app:
  image: 471112617705.dkr.ecr.us-east-1.amazonaws.com/vprofile-app-image
  tag: "40"
  replicas: 1
  port: 8080

db:
  image: rishanu68/vprofiledb
  replicas: 1
  port: 3306 
  password: dnByb2RicGFzcw==   # base64: vprodbpass
  storageSize: 3Gi
  storageClassName: default

memcache:
  image: memcached
  replicas: 1
  port: 11211

rabbitmq:
  image: rabbitmq
  replicas: 1
  port: 5672
  user: guest
  password: Z3Vlc3Q=

ingress:
  ingressClassName: alb
